### ISSUE TITLE
Lark dependency?

### ISSUE THREAD

**Issue by AnnanFay** [evandroforks/HighlightWords#1]
I'm getting the error `ModuleNotFoundError: No module named 'lark'` when the plugin is loaded.

I assume lark needs to be added to `dependencies.json`?

Let me know if you need more info or can't reproduce, could be something else.

**Comment by AnnanFay** [comment]
Not sure what the issue is but figured out how `dependencies.json` actually works so closing this for now while I debug some more.

**Comment by evandrocoan** [comment]
Additionally, the lark dependency is called pushdownparser on dependencies.json.

**Comment by evandrocoan** [comment]
I upped this package to Python 3.8 (because of a bug in lark and the new version of lark does not support Python 3.3 anymore) and the default package control yet does not support dependencies for python 3.8. It works for me because I added support to Python 3.8 dependencies on my fork on Package Control: https://github.com/evandrocoan/PackagesManager

**Comment by AnnanFay** [comment]
Thanks! Changing to use PackagesManager did fix the issue.
